ReactDjangoProject (school)/school/mainSchool/urls.py
from django.urls import path
from . import views

app_name = 'mainSchool'

urlpatterns = [
    path('', views.home, name='home'),
    path('news/', views.news, name='news'),
    path('reports/', views.reports, name='reports'),
    path('forms/', views.SchoolForms.as_view(), name='forms'),
    path('forms/add-student', views.AddStudentView.as_view(), name='addStud'),
    path('forms/show-students', views.ShowStudentView.as_view(), name='showStud'),
    path('forms/update-teacher-class', views.UpdateTeacherClassView.as_view(), name='updateTeacherClass'),
    path('forms/delete-student', views.DeleteStudentView.as_view(), name='deleteStudent')
]

ReactDjangoProject (school)/school/school/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include, re_path

from mainSchool.views import page_not_found, ReportsApiView
from school import routers, settings
from .utils import CustomAuthToken, CustomAuthTokenLogout

# Обращение к View осуществляется в виде: 'namespace_name:app_url_name'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainSchool.urls', namespace='mainSchool')),
    path('', include('users.urls', namespace='users')),
    path('api/v1/', include(routers.router.urls)),
    path('auth/token/login/', CustomAuthToken.as_view()),
    path('auth/token/logout/', CustomAuthTokenLogout.as_view()),
    re_path(r'^auth/', include('djoser.urls')),
    path('api/v1/reports', ReportsApiView.as_view()),
    path("__debug__/", include("debug_toolbar.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
handler_404 = page_not_found

admin.site.site_header = "Панель администрирования"
admin.site.index_title = "МБОУ СОШ №6"

ReactDjangoProject (school)/school/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.user_logout, name='logout'),
]

ReactDjangoProject (school)/school/templates/base-nav.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'mainSchool/css/index.css' %}" />
</head>
<body>
<div class="background"></div>
<div class="header">
    <h1><a href="{% url 'mainSchool:home' %}">МБОУ СОШ №6</a></h1>
    <nav>
        <ul>
            {% for n in nav_menu %}
            <li><a href="{% url n.slug %}">{{ n.name }}</a></li>
            {% endfor %}
            {% if user.is_authenticated %}
                {% if user.first_name %}
                    <li>{{ user.first_name }} | <a href="{% url 'users:logout' %}">ВЫЙТИ</a></li>
                {% else %}
                    <li>{{ user.username }} | <a href="{% url 'users:logout' %}">ВЫЙТИ</a></li>
                {% endif %}
            {% else %}
            <li><a href="{% url 'users:login' %}">ВОЙТИ</a></li>
            {% endif %}
        </ul>
    </nav>
</div>
{% block content %}
{% endblock %}
</body>
</html>